// Bundles vendor/<name>/SKILL.md into a generated TypeScript module, so the Worker can offer them
// as slash commands with no runtime storage or network access. Mirrors the approach
// workshop-backend/scripts/build-format-blueprints.mjs uses for format blueprints.
//
// Each entry is validated with the shared SKILL.md frontmatter parser (the same one
// gatekeeper-context uses), so a malformed vendor file fails the build instead of silently
// deploying a broken slash command.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseSkillManifest } from "@gadgets/workshop-shared/agent-skill";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const vendorDir = join(pkgRoot, "vendor");
const outFile = join(pkgRoot, "src", "generated", "skills.ts");

let dirents = (await readdir(vendorDir, { withFileTypes: true }))
    .filter(d => d.isDirectory())
    .toSorted((a, b) => a.name.localeCompare(b.name));

// Recursively lists files under `dir`, returning paths relative to `vendorDir`.
async function listFilesRelative(dir) {
  let out = [];
  for (let entry of await readdir(dir, { withFileTypes: true })) {
    let full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...await listFilesRelative(full));
    else out.push(full.slice(vendorDir.length + 1).replaceAll("\\", "/"));
  }
  return out;
}

let skills = [];
let docs = [];
let seenNames = new Map();
for (let dirent of dirents) {
  let skillPath = `${dirent.name}/SKILL.md`;
  let content = await readFile(join(vendorDir, skillPath), "utf8");
  let manifest = parseSkillManifest("SKILL.md", content);

  let duplicate = seenNames.get(manifest.name);
  if (duplicate) {
    throw new Error(`vendor/${duplicate}/SKILL.md and vendor/${skillPath} share name "${manifest.name}"`);
  }
  seenNames.set(manifest.name, skillPath);

  skills.push({ path: skillPath, name: manifest.name, description: manifest.description, content });

  // Bundle any references/assets alongside SKILL.md, so skill text can point agents at them via
  // read(id) instead of a bare (nonexistent, in this runtime) filesystem path. Only SKILL.md itself
  // is a slash command; these are plain documents.
  let skillDir = join(vendorDir, dirent.name);
  for (let subdir of ["references", "assets"]) {
    let subdirPath = join(skillDir, subdir);
    if (!existsSync(subdirPath)) continue;
    for (let relPath of await listFilesRelative(subdirPath)) {
      docs.push({ id: relPath, content: await readFile(join(vendorDir, relPath), "utf8") });
    }
  }
}

let generated = `// GENERATED by scripts/build-skills.mjs -- do not edit.
//
// The vendored Agent Skills from vendor/, bundled so the Worker can offer them as slash commands
// with no runtime storage or network access. See vendor/VENDORED_FROM.md for provenance.

export type BundledSkill = {
  // Vendor-relative path, e.g. "space-xhs-title/SKILL.md".
  path: string;
  // Validated frontmatter "name" -- the slash command name.
  name: string;
  // Validated frontmatter "description".
  description: string;
  // Full SKILL.md text, including frontmatter.
  content: string;
};

export const CREATOR_BUDDY_SKILLS: BundledSkill[] = ${JSON.stringify(skills, null, 2)};

// A skill's references/*.md, references/*.json, or assets/*.html companion document. \`id\` is the
// vendor-relative path (e.g. "xhs-html/references/style-registry.md") and is what a skill's own
// text should tell the agent to pass to CreatorBuddy.read(id).
export type BundledDoc = {
  id: string;
  content: string;
};

export const CREATOR_BUDDY_DOCS: BundledDoc[] = ${JSON.stringify(docs, null, 2)};
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, generated);

console.log(`Bundled ${skills.length} skill(s) and ${docs.length} doc(s) from ${vendorDir} -> ${outFile}`);
