// Bundles vendor/<name>/SKILL.md into a generated TypeScript module, so the Worker can offer them
// as slash commands with no runtime storage or network access. Mirrors the approach
// workshop-backend/scripts/build-format-blueprints.mjs uses for format blueprints.
//
// Each entry is validated with the shared SKILL.md frontmatter parser (the same one
// gatekeeper-context uses), so a malformed vendor file fails the build instead of silently
// deploying a broken slash command.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseSkillManifest } from "@gadgets/workshop-shared/agent-skill";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const vendorDir = join(pkgRoot, "vendor");
const outFile = join(pkgRoot, "src", "generated", "skills.ts");

let dirents = (await readdir(vendorDir, { withFileTypes: true }))
    .filter(d => d.isDirectory())
    .toSorted((a, b) => a.name.localeCompare(b.name));

let entries = [];
let seenNames = new Map();
for (let dirent of dirents) {
  let path = `${dirent.name}/SKILL.md`;
  let content = await readFile(join(vendorDir, path), "utf8");
  let manifest = parseSkillManifest("SKILL.md", content);

  let duplicate = seenNames.get(manifest.name);
  if (duplicate) {
    throw new Error(`vendor/${duplicate}/SKILL.md and vendor/${path} share name "${manifest.name}"`);
  }
  seenNames.set(manifest.name, path);

  entries.push({ path, name: manifest.name, description: manifest.description, content });
}

let generated = `// GENERATED by scripts/build-skills.mjs -- do not edit.
//
// The vendored Agent Skills from vendor/, bundled so the Worker can offer them as slash commands
// with no runtime storage or network access. See vendor/VENDORED_FROM.md for provenance.

export type BundledSkill = {
  // Vendor-relative path, e.g. "space-xhs-title/SKILL.md".
  path: string;
  // Validated frontmatter "name" -- the slash command name.
  name: string;
  // Validated frontmatter "description".
  description: string;
  // Full SKILL.md text, including frontmatter.
  content: string;
};

export const CREATOR_BUDDY_SKILLS: BundledSkill[] = ${JSON.stringify(entries, null, 2)};
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, generated);

console.log(`Bundled ${entries.length} skill(s) from ${vendorDir} -> ${outFile}`);
